// Tariflerdeki Türkçe ülke adı → ISO 3166-1 alpha-2 kodu. Pasaport
// damgalarında kıta simgesi yerine ülkenin kendi bayrağını göstermek için
// kullanılır (ör. Türkiye tarifleri "europe" kıtasında olduğu için eskiden
// AB bayrağıyla görünüyordu).
const COUNTRY_CODES = {
  'ABD': 'US',
  'Afganistan': 'AF',
  'Almanya': 'DE',
  'Angola': 'AO',
  'Arjantin': 'AR',
  'Avustralya': 'AU',
  'Avusturya': 'AT',
  'Azerbaycan': 'AZ',
  'Bangladeş': 'BD',
  'Belçika': 'BE',
  'Bosna-Hersek': 'BA',
  'Botsvana': 'BW',
  'Brezilya': 'BR',
  'Bulgaristan': 'BG',
  'Butan': 'BT',
  'Cezayir': 'DZ',
  'Çek Cumhuriyeti': 'CZ',
  'Çin': 'CN',
  'Danimarka': 'DK',
  'Ekvador': 'EC',
  'El Salvador': 'SV',
  'Endonezya': 'ID',
  'Eritre': 'ER',
  'Ermenistan': 'AM',
  'Etiyopya': 'ET',
  'Fas': 'MA',
  'Fiji': 'FJ',
  'Fildişi Sahili': 'CI',
  'Filipinler': 'PH',
  'Fransa': 'FR',
  'Fransız Polinezyası': 'PF',
  'Gana': 'GH',
  'Guatemala': 'GT',
  'Gürcistan': 'GE',
  'Güney Afrika': 'ZA',
  'Güney Kore': 'KR',
  'Hindistan': 'IN',
  'Hollanda': 'NL',
  'Hawaii (ABD)': 'US',
  'İngiltere': 'GB',
  'İran': 'IR',
  'İrlanda': 'IE',
  'İskoçya': 'GB',
  'İspanya': 'ES',
  'İsrail': 'IL',
  'İsveç': 'SE',
  'İsviçre': 'CH',
  'İtalya': 'IT',
  'Japonya': 'JP',
  'Kamboçya': 'KH',
  'Kamerun': 'CM',
  'Kanada': 'CA',
  'Kazakistan': 'KZ',
  'Kenya': 'KE',
  'Kırgızistan': 'KG',
  'Kolombiya': 'CO',
  'Kongo': 'CG',
  'Kore': 'KR',
  'Kosta Rika': 'CR',
  'Küba': 'CU',
  'Laos': 'LA',
  'Liberya': 'LR',
  'Libya': 'LY',
  'Lübnan': 'LB',
  'Macaristan': 'HU',
  'Madagaskar': 'MG',
  'Maldivler': 'MV',
  'Malezya': 'MY',
  'Mali': 'ML',
  'Mauritius': 'MU',
  'Meksika': 'MX',
  'Mısır': 'EG',
  'Moğolistan': 'MN',
  'Mozambik': 'MZ',
  'Myanmar': 'MM',
  'Nepal': 'NP',
  'Nijerya': 'NG',
  'Nikaragua': 'NI',
  'Özbekistan': 'UZ',
  'Pakistan': 'PK',
  'Panama': 'PA',
  'Papua Yeni Gine': 'PG',
  'Paraguay': 'PY',
  'Peru': 'PE',
  'Polonya': 'PL',
  'Portekiz': 'PT',
  'Romanya': 'RO',
  'Ruanda': 'RW',
  'Rusya': 'RU',
  'Samoa': 'WS',
  'Senegal': 'SN',
  'Singapur': 'SG',
  'Sırbistan': 'RS',
  'Somali': 'SO',
  'Sri Lanka': 'LK',
  'Sudan': 'SD',
  'Suriye': 'SY',
  'Şili': 'CL',
  'Tanzanya': 'TZ',
  'Tayland': 'TH',
  'Tayvan': 'TW',
  'Tunus': 'TN',
  'Türkiye': 'TR',
  'Uganda': 'UG',
  'Ukrayna': 'UA',
  'Ürdün': 'JO',
  'Venezuela': 'VE',
  'Vietnam': 'VN',
  'Yemen': 'YE',
  'Yeni Kaledonya': 'NC',
  'Yeni Zelanda': 'NZ',
  'Yunanistan': 'GR',
  'Zambiya': 'ZM',
  'Zimbabwe': 'ZW',
};

const codeToFlag = (code) =>
  String.fromCodePoint(...[...code].map(c => 0x1f1e6 + c.charCodeAt(0) - 65));

// "Lübnan / Filistin" gibi birden fazla ülkeli adlarda ilk ülkenin bayrağı
// kullanılır. Bilinmeyen ülke (ör. kullanıcının gönderdiği tarif) için null
// döner -- çağıran taraf kıta simgesine düşer.
export function getCountryFlag(country) {
  if (!country) return null;
  const code = COUNTRY_CODES[country] || COUNTRY_CODES[country.split('/')[0].trim()];
  return code ? codeToFlag(code) : null;
}
